### PR TITLE
add questions, answers, and feedback to the workshop page

### PR DESCRIPTION
**Pull request by bast**
This change adds all questions, answers, and feedback at the bottom of the workshop page.

### CODE REVIEW

**Comment by bast** [comment]
There are names mentioned in 3 places (AFAICS) but only praise for how great helpers they were so I left it but I can redact it out if you prefer.

**Review by rkdarst — APPROVED** [review]
I just saw me, Radovan, and Thor, and don't have time to look closer and don't remember from before.  Anyone else?

I am fine with my name but if anyone doesn't want theirs, I'd remove them all.

**Review by annefou — APPROVED** [review]
I think it is a very good idea. Especially if one wants to follow the lesson on its own.

**Comment by bast** [comment]
- I also think this can be really useful for offline learning (one learner could not attend day 2 and read up on their own and we will have a short question and answer video call soon).
- Do you prefer me to remove all names?

**Comment by annefou** [comment]
For names, they could be replaced by the name of the section taught; I am not sure. As is, I am not sure they are very useful for offline teaching or for future online teaching.

**Comment by bast** [comment]
OK I will better remove names. Force-push coming up in not too long.

**Pull request merged**
